# Generated by Django 2.2.12 on 2020-04-11 19:11

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinfo',
            name='detail',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='课程详情'),
        ),
        migrations.AlterModelTable(
            name='courseinfo',
            table='edu_courses',
        ),
        migrations.AlterModelTable(
            name='lessoninfo',
            table='edu_lessons',
        ),
        migrations.AlterModelTable(
            name='sourceinfo',
            table='edu_sources',
        ),
        migrations.AlterModelTable(
            name='videoinfo',
            table='edu_videos',
        ),
    ]
