# Generated by Django 3.0.5 on 2020-04-12 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20200411_1911'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseinfo',
            options={'ordering': ['-add_time'], 'verbose_name': '课程信息', 'verbose_name_plural': '课程信息'},
        ),
        migrations.AlterField(
            model_name='videoinfo',
            name='url',
            field=models.FileField(upload_to='courses/%y/%m/%d', verbose_name='视频'),
        ),
    ]
