# Generated by Django 2.1 on 2020-04-08 11:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=200, upload_to='banners/%y/%m/%d', verbose_name='轮播图片')),
                ('url', models.URLField(verbose_name='轮播链接')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '轮播图信息',
                'verbose_name_plural': '轮播图信息',
                'db_table': 'gl_banner_info',
            },
        ),
        migrations.CreateModel(
            name='EmailVerifyCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, verbose_name='邮箱')),
                ('code', models.CharField(max_length=20, verbose_name='验证码')),
                ('send_type', models.CharField(choices=[('register', '注册激活'), ('forget', '重置密码'), ('change', '修改邮箱')], max_length=15, verbose_name='发送类别')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='发送时间')),
            ],
            options={
                'verbose_name': '邮箱验证码',
                'verbose_name_plural': '邮箱验证码',
                'db_table': 'gl_email_verify_code',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('image', models.ImageField(blank=True, max_length=200, null=True, upload_to='users/%y/%m/%d', verbose_name='用户头像')),
                ('nick_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='用户昵称')),
                ('birthday', models.DateTimeField(blank=True, null=True, verbose_name='用户生日')),
                ('gender', models.CharField(choices=[('男', '男'), ('女', '女')], default='男', max_length=6, verbose_name='用户性别')),
                ('address', models.CharField(blank=True, max_length=300, null=True, verbose_name='用户地址')),
                ('phone', models.CharField(max_length=11, verbose_name='用户手机')),
                ('is_start', models.BooleanField(default=False, verbose_name='是否激活')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
                'db_table': 'gl_user_info',
            },
        ),
    ]
