# Generated by Django 2.2.12 on 2020-04-11 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200410_1815'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bannerinfo',
            table='edu_banners',
        ),
        migrations.AlterModelTable(
            name='emailverifycode',
            table='edu_email_verify_code',
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='edu_users',
        ),
    ]
