# Generated by Django 2.2.12 on 2020-04-11 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userask',
            table='edu_userasks',
        ),
        migrations.AlterModelTable(
            name='usercomment',
            table='edu_usercomments',
        ),
        migrations.AlterModelTable(
            name='usercourse',
            table='edu_usercourses',
        ),
        migrations.AlterModelTable(
            name='userlove',
            table='edu_favourites',
        ),
        migrations.AlterModelTable(
            name='usermessage',
            table='edu_usermessages',
        ),
    ]
