# Generated by Django 3.0.5 on 2020-04-12 12:44

import DjangoUeditor.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='城市名称')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '城市信息',
                'verbose_name_plural': '城市信息',
                'db_table': 'edu_citys',
            },
        ),
        migrations.CreateModel(
            name='OrgInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='机构名称')),
                ('image', models.ImageField(upload_to='orgs/%y/%m/%d', verbose_name='机构封面')),
                ('study_num', models.IntegerField(default=0, verbose_name='学习人数')),
                ('address', models.CharField(max_length=200, verbose_name='机构地址')),
                ('org_category', models.CharField(choices=[('gr', '个人'), ('gx', '高校'), ('pxjg', '培训机构')], default='pxjg', max_length=16, verbose_name='机构类别')),
                ('desc', models.CharField(max_length=300, verbose_name='机构简介')),
                ('detail', DjangoUeditor.models.UEditorField(default='', verbose_name='机构详情')),
                ('course_num', models.IntegerField(default=0, verbose_name='机构课程数')),
                ('click_num', models.IntegerField(default=0, verbose_name='访问量')),
                ('love_num', models.IntegerField(default=0, verbose_name='收藏人数')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.CityInfo', verbose_name='所属城市')),
            ],
            options={
                'verbose_name': '机构信息',
                'verbose_name_plural': '机构信息',
                'db_table': 'edu_orgs',
            },
        ),
        migrations.CreateModel(
            name='TeacherInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='教师姓名')),
                ('image', models.ImageField(upload_to='teachers/%y/%m/%d', verbose_name='教师头像')),
                ('age', models.IntegerField(default=30, verbose_name='教师年龄')),
                ('work_year', models.IntegerField(default=3, verbose_name='工作年限')),
                ('work_position', models.CharField(max_length=20, verbose_name='工作职位')),
                ('work_style', models.CharField(max_length=20, verbose_name='教学特点')),
                ('click_num', models.IntegerField(default=0, verbose_name='访问量')),
                ('love_num', models.IntegerField(default=0, verbose_name='收藏人数')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.OrgInfo', verbose_name='所属机构')),
            ],
            options={
                'verbose_name': '教师信息',
                'verbose_name_plural': '教师信息',
                'db_table': 'edu_teachers',
            },
        ),
    ]
