# Generated by Django 2.1 on 2020-04-09 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orginfo',
            name='org_category',
            field=models.CharField(choices=[('gr', '个人'), ('gx', '高校'), ('pxjg', '培训机构')], default='培训机构', max_length=16, verbose_name='机构类别'),
        ),
    ]
