# Generated by Django 2.2.12 on 2020-04-11 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0003_auto_20200411_1613'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cityinfo',
            table='edu_citys',
        ),
        migrations.AlterModelTable(
            name='orginfo',
            table='edu_orgs',
        ),
        migrations.AlterModelTable(
            name='teacherinfo',
            table='edu_teachers',
        ),
    ]
